resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/21.yaml

packages:
- .

extra-deps:
- smcdel-1.2.0@sha256:626f7daa9e15631eb37c43cbd4a24a45de90ecc579a9f84d21ead1fdd9526cb3,5552
- git: https://github.com/m4lvin/cudd.git
  commit: 32f7d6b764a80bbf8f84c07e2c1d691469aaaba0
- HasCacBDD-0.1.0.3
