resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/21.yaml

packages:
- .

extra-deps:
- git: https://github.com/jrclogic/SMCDEL.git
  commit: b20eeaac9900879b1636fba9a0968a80de4eb1c6
- git: https://github.com/m4lvin/cudd.git
  commit: 32f7d6b764a80bbf8f84c07e2c1d691469aaaba0
- HasCacBDD-0.1.0.3
